{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE, PATCH
    nginx.ingress.kubernetes.io/enable-cors: "true"
    {{- if not .Values.local }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
  name: undistro-ingress-ui
  namespace: undistro-system
spec:
  ingressClassName: nginx
  rules:
    -
      http:
        paths:
          -
            backend:
              service:
                name: undistro-webhook-service
                port:
                  number: 2020
            path: /
            pathType: Prefix
  tls:
    -
      hosts:
      {{with .Values.ingress.ipAddresses}}
      {{- range . }}
        - {{ . }}
      {{- end }}
      {{end}}
      {{- range .Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}

