---
apiVersion: v2
appVersion: v0.10.0-undistro
description: "A Pinniped Supervisor Helm chart for Kubernetes"
home: "http://pinniped.dev/"
maintainers:
  - name: getupio-undistro
    url: https://undistro.io/
name: pinniped-supervisor
type: application
version: 0.10.0-undistro
