name: undistro-release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release UnDistro
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Set up Node 15
        uses: actions/setup-node@v2
        with:
          node-version: "15"
        id: node

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.undistro.io
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: vars from bash
        run: ./hack/version.sh

      - name: Build UI
        working-directory: ./UI
        run: |
          yarn
          yarn build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: helm chart-push
        working-directory: ./charts
        env:
          HELM_LOGIN: ${{ secrets.REGISTRY_LOGIN }}
          HELM_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          helm plugin install https://github.com/getupio-undistro/helm-push.git
          helm repo add undistro https://registry.undistro.io/chartrepo/library
          helm chart-push cert-manager undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push cluster-api undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push undistro undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push undistro-aws undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push kyverno undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push ingress-nginx undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push pinniped-concierge undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push pinniped-supervisor undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push metallb undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push undistro-openstack undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push cloud-provider-openstack undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
          helm chart-push kube-prometheus-stack undistro --username $HELM_LOGIN --password  $HELM_PASSWORD --force
